### ISSUE TITLE
Compatibility problems

### ISSUE THREAD

**Issue by NoiSek** [DannyTheVito/Caddo-911-Parser#1]
Looks great, but I can't run this on my fridge 🎱

**Comment by DannyTheVito** [comment]
What's the make and model of your fridge? Please paste any output you get when you attempt to run it.

**Comment by NoiSek** [comment]
Console output when running `cops.py`:
```
  Well the years start coming and they don't stop coming
  Fed to the rules and I hit the ground running
  Didn't make sense not to live for fun
  Your brain gets smart but your head gets dumb
  So much to do, so much to see
  So what's wrong with taking the back streets?
  You'll never know if you don't go
  You'll never shine if you don't glow
```

**Comment by DannyTheVito** [comment]
It might be an issue with your system. Please forward me anything in a Styrofoam container or wrapped in aluminum foil.

**Comment by NoiSek** [comment]
Will do, thanks for responding so fast! 💯
